ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path



from cart import views


app_name="cart"
urlpatterns = [
path('addtocart/<int:i>',views.Addtocart.as_view(),name="addtocart"),
path('cartdecrement/<int:i>',views.Cartdecrement.as_view(),name="cartdecrement"),
path('cartremove/<int:i>',views.Cartremove.as_view(),name="cartremove"),
path('cartview/',views.CartView.as_view(),name="cartview"),
path('checkout/',views.Checkout.as_view(),name="checkout"),
path('payment_success/',views.Payment_success.as_view(),name="payment_success"),
path('yourorder',views.Yourorder.as_view(),name="yourorder")
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
from django.conf.urls.static import static
from django.conf import settings
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views



app_name="search"
urlpatterns = [
path('',views.SearchView.as_view(),name="search"),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path


from shop import views
app_name="shop"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.CategoryView.as_view(),name="categories"),
    path('products/<int:i>',views.ProductView.as_view(),name="products"),
    path('productdetail/<int:i>',views.ProductDetailView.as_view(),name="productdetail"),
    path('register', views.Register.as_view(), name="register"),
    path('login', views.Userlogin.as_view(), name="userlogin"),
    path('logout', views.Userlogout.as_view(), name="userlogout"),
    path('addcategory',views.AddCategory.as_view(),name="addcategory"),
    path('addproduct',views.AddProduct.as_view(),name="addproduct")
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.product.price*self.quantity

class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    order_id=models.CharField(max_length=20,blank=True)
    amount=models.IntegerField()
    address=models.TextField()
    phone=models.IntegerField()
    payment_method=models.CharField(max_length=30)
    ordered_date=models.DateTimeField(auto_now_add=True)
    is_ordered=models.BooleanField(default=False)
    delivery_status=models.CharField(max_length=20,default="Pending")

    def __str__(self):
        return self.order_id


class Order_items(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name="items")
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()

    def __str__(self):
        return self.order.order_id

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/forms.py
from django import forms
from cart.models import Order
class OrderForm(forms.ModelForm):
    payment_choices=(('COD','COD'),('ONLINE','ONLINE'))
    payment_method=forms.ChoiceField(choices=payment_choices)
    class Meta:
        model=Order
        fields=['address','phone','payment_method']

ecommerce/cart/views.py
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from shop.models import Product
from cart.models import Cart
import razorpay

from cart.models import Order_items


from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
@method_decorator(login_required,name="dispatch")
class Addtocart(View):
    def get(self,request,i):
        #product
        p=Product.objects.get(id=i)#checks whether the product is already added to cart table
        #user
        u=request.user
        try:
            c=Cart.objects.get(user=u,product=p)
            c.quantity+=1#increments quantity by 1
            c.save()
        except:#if product does not exist
            c=Cart.objects.create(user=u,product=p,quantity=1)#creates a new record with quantity=1
            c.save()
        return redirect('cart:cartview')


class CartView(View):
    def get(self,request):
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total=total+i.subtotal()
        context={'cart':c,'total':total}
        return render(request,'cart.html',context)

class Cartdecrement(View):
    def get(self,request,i):
        try:
            c=Cart.objects.get(id=i)
            if(c.quantity>1):
                c.quantity-=1
                c.save()
            else:
                c.delete()
        except:
            pass
        return redirect('cart:cartview')

class Cartremove(View):
    def get(self,request,i):
        try:
            c=Cart.objects.get(id=i)
            c.delete()
        except:
            pass
        return redirect('cart:cartview')
import uuid
from cart.forms import OrderForm
class Checkout(View):
    def post(self,request):
        form_instance=OrderForm(request.POST)
        if form_instance.is_valid():
            o=form_instance.save(commit=False)
            #adds current user
            u=request.user
            o.user=u


            #adds total amount
            c=Cart.objects.filter(user=u)
            total=0
            for i in c:
                total+=i.subtotal()
                print(total)
                o.amount=total
                o.save()
                if(o.payment_method=="ONLINE"):
                    #create a razorpay connetion using keys
                    client=razorpay.Client(auth=('rzp_test_RnTSdnViOdXHUR','YWDjwbgKbd7PiKeaiQ7WyiT7'))
                    #2 creates a new order in razorpsy
                    response_payment=client.order.create({'amount':(o.amount)*100,'currency':'INR'})
                    print(response_payment)
                    #retrieves the order id from the response_payment
                    id=response_payment['id']
                    #saves it in order table
                    o.order_id=id
                    o.save()
                    context={'payment':response_payment}
                    return render(request,'payment.html',context)

                else:  # COD
                    # updates order table
                    id = 'ord_cod' + uuid.uuid4().hex[:14]
                    o.order_id = id
                    o.is_ordered = True
                    o.save()
                    # add products to order_items
                    for i in c:
                        item = Order_items.objects.create(order=o, product=i.product, quantity=i.quantity)
                        item.save()
                        item.product.stock -= i.quantity
                        item.product.save()
                        # delete cart table
                    c.delete()
                    return render(request, 'payment.html')
                    pass

    def get(self,request):
        form_instance=OrderForm()
        context={'form':form_instance}
        return render(request,'checkout.html',context)

# @csrf_exempt
# def f():
#     pass

#csrf_exempt-to ignore csrf verification
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from cart.models import Order,Order_items
@method_decorator(csrf_exempt,name="dispatch")
class Payment_success(View):
    def post(self,request):
        print(request.user.username)
        response=request.POST
        # print(response)
        #updates order table
        id=response['razorpay_order_id']#READS THE ORDER ID FROM THE RAZORPAY RESPONSE
        o=Order.objects.get(order_id=id)#RETRIEVES THE ORDER RECORD MATCHING WITH THID ORDERID
        o.is_ordered=True#set is_ordered status to true
        o.save()
        #add products into order_items table
        u=request.user
        c=Cart.objects.filter(user=u)
        for i in c:
            item=Order_items.objects.create(order=o,product=i.product,quantity=i.quantity)
            item.save()
            item.product.stock-=i.quantity
            item.product.save()
        #delete cart table
        c.delete()
        return render(request,'payment_success.html')

class Yourorder(View):
    def get(self, request):
        user = request.user
        orders = Order.objects.filter(user=user).order_by('-id')
        context = {'orders': orders}
        return render(request, 'yourorder.html', context)

ecommerce/search/views.py
from django.shortcuts import render
from django.views import View
from shop.models import Product
from django.db.models import Q


# Create your views here.
class SearchView(View):
    def get(get, request):
        query = request.GET['q']  # reads the keyword
        print(query)
        # 0RM query to filter records from table(two or more records)
        p = Product.objects.filter(Q(name__icontains=query) |
                                Q(description__icontains=query) |
                                Q(price__icontains=query)  # case insensitive
                                )
        context = {'products': p,'query':query}
        return render(request, 'search.html', context)

ecommerce/templates/addcategory.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container w-75 p-5 mt-5 border border-2 fst-italic text-center">
 <h3>AddCategoryDetails</h3>

 <form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <div class="mb-3">
   <input type="submit" class="btn btn-light">
  </div>
 </form>

</div>
{% endblock %}

ecommerce/templates/addstock.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container w-75 p-5 mt-5 border border-2 fst-italic text-center">
    <h3>update stock</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3">Add Product</button>
    </form>
</div>
{% endblock %}

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% block content %}
 <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Cart</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start Cart  -->
    <div class="cart-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-main table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>subtotal</th>
                                    <th>Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for i in cart %}
                                <tr>
                                    <td class="thumbnail-img">
                                        <a href="#">
									<img class="img-fluid" src="{{i.product.image.url}}" alt="" />
								</a>
                                    </td>
                                    <td class="name-pr">
                                        <a href="#">
									{{i.product.name}}
								</a>
                                    </td>
                                    <td class="price-pr">
                                        <p>{{i.product.price}}</p>
                                    </td>
                                    <td class="quantity-box">
                                    <p>{{i.quantity}}</p>
                                    </td>
                                    <td class="total-pr">
                                        <p>{{i.subtotal}}</p>
                                    </td>
                                    <td class="remove-pr">
                                        <a href="{% url 'cart:addtocart' i.product.id %}">

									<i class="fas fa-plus"></i>
								</a><a href="{% url 'cart:cartdecrement' i.id%} ">

                                    <i class="fas fa-minus"></i>
                                    </a>
                                        <a href="{% url 'cart:cartremove' i.id %}">
                                            <i class="fas fa-times"></i>
                                        </a>


                                    </td>
                                </tr>

                               {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



            <div class="row my-5">
                <div class="col-lg-8 col-sm-12"></div>
                <div class="col-lg-4 col-sm-12">
                    <div class="order-box">
                        <h3>Order summary</h3>
                        <div class="d-flex">
                            <h4>Sub Total</h4>
                            <div class="ml-auto font-weight-bold">{{total}}</div>
                        </div>

                        <div class="d-flex">
                            <h4>Shipping Cost</h4>
                            <div class="ml-auto font-weight-bold"> Free </div>
                        </div>
                        <hr>
                        <div class="d-flex gr-total">
                            <h5>Grand Total</h5>
                            <div class="ml-auto h5">{{total}}</div>
                        </div>
                        <hr> </div>
                </div>
                <div class="col-12 d-flex shopping-box"><a href="{% url 'cart:checkout' %}" class="ml-auto btn hvr-hover">Checkout</a> </div>
            </div>

        </div>
    </div>
    <!-- End Cart -->
{% endblock %}

ecommerce/templates/categories.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <div id="slides-shop" class="cover-slides">
        <ul class="slides-container">
            <li class="text-center">
                <img src="{% static 'images/banner-01.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'images/banner-02.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'images/banner-03.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <div class="slides-navigation">
            <a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
            <a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
        </div>
    </div>
<div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>OUR COLLECTIONS</h1>
                        <p style="text-align:justify;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
                    </div>
                </div>
            </div><div></div>
   <!-- Start Categories  -->
    <div class="categories-shop">
        <div class="container">
            <div class="row">
                {% for i in cat %}
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="shop-cat-box">
                        <img src="{{i.image.url}}" height="300px" width="100%" alt="" />
                        <a class="btn hvr-hover" href="{% url 'shop:products' i.id %}">{{i.name}}</a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container w-75 p-5 mt-5 border border-2 fst-italic text-center">
 <h3>register</h3>
 <form  method="POST">
  {% csrf_token %}
  {{form|crispy}}
  <div class="mb-3">
   <input type="submit" class="btn btn-light">
  </div>
 </form>
</div>
{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% block content %}
{% if payment %}
<form action="{% url 'cart:payment_success' %}" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_RnTSdnViOdXHUR"
    data-amount={{payment.amount}}
    data-currency="INR"
    data-order_id={{payment.id}}
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="Gaurav Kumar"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
{% else %}
<h2>your order is placed successfully</h2>
{% endif %}
{% endblock%}

ecommerce/templates/payment_success.html
{% extends 'base.html' %}
{% block content %}
payment successfully completed
{% endblock %}

ecommerce/templates/productdetail.html
{% extends 'base.html' %}
{% block content %}
<!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>product details</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">detail</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start About Page  -->
    <div class="about-box-main">
        <div class="container">
            <div class="row">
				<div class="col-lg-6">
                    <div class="banner-frame"> <img class="img-fluid" src="{{product.image.url}}" alt="" />
                    </div>
                </div>
                <div class="col-lg-6">
                    <h2 class="noo-sh-title-top"><span>{{product.name}}</span></h2>
                    <p>Rs{{product.price}}</p>
                    <p>currently {{product.stock}} items available</p>
                    <h4>short description</h4>
                    <p>{{product.description}}</p>
                    {% if user.is_superuser == True %} <!--admin user-->
					<a class="btn hvr-hover" href="#">add stock</a>
                    {% else %}<!--normal user-->
                    {% if product.stock > 0 %}
                    <a class="btn hvr-hover" href="{% url 'cart:addtocart' product.id %}">add to cart</a>
                      {% else %}
                        <h4>out of stock</h4>
                    {% endif %}
                    {% endif %}
                </div>
            </div>

            </div>
{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <img src="{{cat.image.url}}" height="400px" width="100%">
</div>
<div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>{{cat.name}}</h1>
                        <p style="text-align:justify;">{{cat.description}}</p>
                    </div>
                </div>
            </div><div></div>
        {% for i in cat.products.all  %}

        {% endfor %}
             <div class="row special-list">
             {% for i in cat.products.all %}
                <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover">
                            <div class="type-lb">
                                <p class="sale">Sale</p>
                            </div>
                            <img src="{{i.image.url}}" class="img-fluid" alt="Image">
                            <div class="mask-icon">
                                <ul>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                </ul>
                                <a class="cart" href="{% url 'shop:productdetail' i.id %}">details</a>
                            </div>
                        </div>
                        <div class="why-text">
                            <h4>{{i.name}}</h4>
                            <h5>{{i.price}}</h5>
                        </div>
                    </div>
                </div>


{% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container w-75 p-5 mt-5 border border-2 fst-italic text-center">
 <h3>register</h3>
 <form  method="POST">
  {% csrf_token %}
  {{form|crispy}}
  <div class="mb-3">
   <input type="submit" class="btn btn-light">
  </div>
 </form>
</div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container w-75 p-5 mt-5 border border-2 fst-italic text-center">
    <div class="products-box">
        <div class="container">

            <h2>you have searched for <span>{{query}}</span></h2>
            {% if products %}
            <div class="row special-list">


             {% for i in products %}
                <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover">
                            <div class="type-lb">
                                <p class="sale">Sale</p>
                            </div>
                            <img src="{{i.image.url}}" class="img-fluid" height="300px" width="100%" alt="Image">
                            <div class="mask-icon">
                                <ul>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                </ul>
                                <a class="cart" href="{% url 'shop:productdetail' i.id %}">details</a>
                            </div>
                        </div>
                        <div class="why-text">
                            <h4>{{i.name}}</h4>
                            <h5>{{i.price}}</h5>
                        </div>
                    </div>
                </div>


{% endfor %}
            </div>
 {% else %}
<h4 class="text-center">NO RESULTS FOUND</h4>
 {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

ecommerce/templates/yourorder.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<h2 class="text-center mb-4">Your Orders</h2>

{% for o in orders %}
<div class="card p-4 mb-4 shadow">

    <h4>Order_no: <strong>order_{{ o.id }}</strong></h4>
    <p>Ordered on: <span class="text-danger">{{ o.ordered_date }}</span></p>
    <p>Order Total: ₹{{ o.amount }}</p>
    <p>Status: <span class="text-warning">{{ o.delivery_status }}</span></p>

    <hr>

    {% for item in o.items.all %}
    <div class="row p-3">

        <!-- Product Image -->
        <div class="col-md-4">
            <img src="{{ item.product.image.url }}" class="img-fluid" style="height:180px; width:auto;">
        </div>

        <!-- Product Info -->
        <div class="col-md-8">
            <h5>Name: {{ item.product.name }}</h5>
            <p>Price: ₹{{ item.product.price }}</p>
            <p>Qty: {{ item.quantity }}</p>
        </div>

    </div>
    {% endfor %}

</div>
{% endfor %}

{% endblock %}